export const PATH = {
  HOME: "/",
  LOGIN: "auth/login",
  REGISTER: "auth/signup",
  CONTACT: "/auth/contact",
  CATEGORY: "/category",
  DETAILCATEGORY: "/category/:id",
  ABOUT: "/about",
  HELP: "/help",
  DEMO1: "/demo1",
  DEMO2: "/demo2",
  FEATURE1: "/feature1",
  FEATURE2: "/feature2",
  PROFILE: "/profile",
  PRODUCTS: "/products",
  PRODUCT_SHOW: "/products/:id",
  PRODUCT_NEW: "/products/new",
  PRODUCT_EDIT: "/products/:id/edit",
  FINDWORK: "/find-work",
  CREATE: "/create",
};
